; Script generated by Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "MacroPad Pro (Dev)"
#define MyAppVersion "1.0.0"
#define MyAppPublisher "Juxtupool"
#define MyAppURL "https://github.com/Juxtupool/APP-TEST"
#define MyAppExeName "MacroPad Pro.exe"
#define SourceDir "dist\MacroPad Pro"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{A3D73045-832F-4386-A785-502690947098}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
; Remove the following line to run in administrative install mode (install for all users.)
PrivilegesRequired=lowest
OutputDir=installer_output
OutputBaseFilename=MacroPad_Pro_Dev_Setup_v{#MyAppVersion}
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; IMPORTANT: Verify this source path points to your build output relative to this .iss file
Source: "{#SourceDir}\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#SourceDir}\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
; Launch App
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#MyAppName}}"; Flags: nowait postinstall skipifsilent

[UninstallDelete]
Type: files; Name: "{app}\config.json"
Type: files; Name: "{app}\profiles.json"

[Code]
var
  DownloadPage: TDownloadWizardPage;

function IsWebView2Installed: Boolean;
var
  key: String;
begin
  // Check 64-bit/32-bit registry keys for WebView2 Runtime
  key := 'SOFTWARE\WOW6432Node\Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}';
  if RegKeyExists(HKEY_LOCAL_MACHINE, key) or RegKeyExists(HKEY_CURRENT_USER, key) then
  begin
    Result := True;
    Exit;
  end;
  
  key := 'SOFTWARE\Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}';
  if RegKeyExists(HKEY_LOCAL_MACHINE, key) or RegKeyExists(HKEY_CURRENT_USER, key) then
    Result := True
  else
    Result := False;
end;

function OnDownloadProgress(const Url, FileName: String; const Progress, ProgressMax: Int64): Boolean;
begin
  if ProgressMax <> 0 then
    Log(Format('  %d of %d bytes downloaded.', [Progress, ProgressMax]));
  Result := True;
end;

procedure InitializeWizard;
begin
  DownloadPage := CreateDownloadPage(SetupMessage(msgWizardPreparing), SetupMessage(msgPreparingDesc), @OnDownloadProgress);
end;

function NextButtonClick(CurPageID: Integer): Boolean;
var
  WV2Url: String;
  WV2Path: String;
  ResultCode: Integer;
begin
  Result := True;

  if (CurPageID = wpReady) and (not IsWebView2Installed) then
  begin
    DownloadPage.Clear;
    // Microsoft Edge WebView2 Bootstrapper URL (Evergreen)
    WV2Url := 'https://go.microsoft.com/fwlink/p/?LinkId=2124703';
    WV2Path := ExpandConstant('{tmp}\MicrosoftEdgeWebview2Setup.exe');
    
    DownloadPage.Add(WV2Url, 'MicrosoftEdgeWebview2Setup.exe', '');
    DownloadPage.Show;
    try
      try
        DownloadPage.SetText('Downloading Microsoft Edge WebView2 Runtime...', 'This might take a while. Please wait.');
        DownloadPage.Download;
        
        DownloadPage.SetText('Installing WebView2 Runtime...', '');
        
        // Run the bootstrapper silently
        if not Exec(WV2Path, '/silent /install', '', SW_HIDE, ewWaitUntilTerminated, ResultCode) then
        begin
          MsgBox('WebView2 Runtime installation failed with code: ' + IntToStr(ResultCode) + '. The application might not work correctly.', mbError, MB_OK);
        end;
        
      except
        MsgBox('Failed to download WebView2 Runtime. Please check your internet connection and try again.', mbError, MB_OK);
      end;
    finally
      DownloadPage.Hide;
    end;
  end;
end;
