; Script generated by Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Overcontrol"
#define MyAppVersion "1.0.5"
#define MyAppPublisher "Overcontrol"
#define MyAppURL "https://github.com/Juxtupool/APP-TEST"
#define MyAppExeName "Overcontrol.exe"
#define SourceDir "dist\Overcontrol"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{A3D73045-832F-4386-A785-502690947098}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
; Remove the following line to run in administrative install mode (install for all users.)
PrivilegesRequired=lowest
OutputDir=installer_output
OutputBaseFilename=Overcontrol_Setup_v{#MyAppVersion}
Compression=lzma
SolidCompression=yes
WizardStyle=modern
SetupIconFile=Icon\Logo.ico

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; IMPORTANT: Verify this source path points to your build output relative to this .iss file
Source: "{#SourceDir}\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#SourceDir}\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
; Launch App
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#MyAppName}}"; Flags: nowait postinstall skipifsilent

[UninstallDelete]
Type: files; Name: "{app}\config.json"
Type: files; Name: "{app}\profiles.json"

[Code]
function GetTickCount: DWord; external 'GetTickCount@kernel32.dll stdcall';

var
  DownloadPage: TDownloadWizardPage;

function IsWebView2Installed: Boolean;
var
  key: String;
begin
  // Check 64-bit/32-bit registry keys for WebView2 Runtime
  key := 'SOFTWARE\WOW6432Node\Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}';
  if RegKeyExists(HKEY_LOCAL_MACHINE, key) or RegKeyExists(HKEY_CURRENT_USER, key) then
  begin
    Result := True;
    Exit;
  end;
  
  key := 'SOFTWARE\Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}';
  if RegKeyExists(HKEY_LOCAL_MACHINE, key) or RegKeyExists(HKEY_CURRENT_USER, key) then
    Result := True
  else
    Result := False;
end;

var
  DownloadStartTick: DWord;

function OnDownloadProgress(const Url, FileName: String; const Progress, ProgressMax: Int64): Boolean;
var
  ElapsedMs: DWord;
  SpeedBytesPerSec: Int64;
  SpeedMB, SpeedMBFrac, SpeedKB, SpeedKBFrac: Int64;
  TransferredMB, TransferredFrac, TotalMB, TotalFrac: Int64;
  Percent: Integer;
  SpeedStr: String;
  ProgressStr: String;
begin
  ElapsedMs := GetTickCount - DownloadStartTick;
  if ElapsedMs = 0 then ElapsedMs := 1; // Avoid division by zero
  
  // Speed in Bytes/sec
  SpeedBytesPerSec := (Progress * 1000) / ElapsedMs;
  
  if SpeedBytesPerSec > 1024 * 1024 then
  begin
    SpeedMB := SpeedBytesPerSec / (1024 * 1024);
    SpeedMBFrac := ((SpeedBytesPerSec mod (1024 * 1024)) * 100) / (1024 * 1024);
    SpeedStr := Format('%d.%02d MB/s', [SpeedMB, SpeedMBFrac]);
  end
  else if SpeedBytesPerSec > 1024 then
  begin
    SpeedKB := SpeedBytesPerSec / 1024;
    SpeedKBFrac := ((SpeedBytesPerSec mod 1024) * 10) / 1024;
    SpeedStr := Format('%d.%d KB/s', [SpeedKB, SpeedKBFrac]);
  end
  else
  begin
    SpeedStr := Format('%d B/s', [SpeedBytesPerSec]);
  end;
  
  TransferredMB := Progress / (1024 * 1024);
  TransferredFrac := ((Progress mod (1024 * 1024)) * 100) / (1024 * 1024);
  
  if ProgressMax > 0 then
  begin
    TotalMB := ProgressMax / (1024 * 1024);
    TotalFrac := ((ProgressMax mod (1024 * 1024)) * 100) / (1024 * 1024);
    Percent := (Progress * 100) / ProgressMax;
    
    ProgressStr := Format('Downloaded %d.%02d MB of %d.%02d MB (%d%%) at %s', [TransferredMB, TransferredFrac, TotalMB, TotalFrac, Percent, SpeedStr]);
    DownloadPage.SetProgress(Progress, ProgressMax);
  end
  else
  begin
    ProgressStr := Format('Downloaded %d.%02d MB at %s', [TransferredMB, TransferredFrac, SpeedStr]);
    DownloadPage.SetProgress(Progress mod 100, 100);
  end;
  
  DownloadPage.SetText('Downloading Microsoft Edge WebView2 Runtime...', ProgressStr);
  Result := True;
end;

procedure InitializeWizard;
begin
  DownloadPage := CreateDownloadPage(SetupMessage(msgWizardPreparing), SetupMessage(msgPreparingDesc), @OnDownloadProgress);
  DownloadPage.AbortButton.Visible := False;
end;

function NextButtonClick(CurPageID: Integer): Boolean;
var
  WV2Url: String;
  WV2Path: String;
  ResultCode: Integer;
begin
  Result := True;

  if (CurPageID = wpReady) and (not IsWebView2Installed) then
  begin
    DownloadPage.Clear;
    // Microsoft Edge WebView2 Bootstrapper URL (Evergreen)
    WV2Url := 'https://go.microsoft.com/fwlink/p/?LinkId=2124703';
    WV2Path := ExpandConstant('{tmp}\MicrosoftEdgeWebview2Setup.exe');
    
    DownloadPage.Add(WV2Url, 'MicrosoftEdgeWebview2Setup.exe', '');
    DownloadPage.Show;
    WizardForm.CancelButton.Visible := False;
    try
      try
        DownloadStartTick := GetTickCount;
        DownloadPage.SetText('Downloading Microsoft Edge WebView2 Runtime...', 'Starting download...');
        DownloadPage.Download;
        
        DownloadPage.SetText('Installing WebView2 (Microsoft System component)...', 'Please wait...');
        DownloadPage.SetProgress(50, 100);
        
        // Run the bootstrapper silently
        if not Exec(WV2Path, '/silent /install', '', SW_HIDE, ewWaitUntilTerminated, ResultCode) then
        begin
          MsgBox('WebView2 Runtime installation failed with code: ' + IntToStr(ResultCode) + '. The application might not work correctly.', mbError, MB_OK);
        end;
        
      except
        MsgBox('Failed to download WebView2 Runtime. Please check your internet connection and try again.', mbError, MB_OK);
      end;
    finally
      DownloadPage.Hide;
      WizardForm.CancelButton.Visible := True;
    end;
  end;
end;
